server:
  port: 6666

spring:
  application:
    name: eventstore
    exchange: user.events.fanout.exchange
    queue: user.default.queue
    databaseName: users
    eventsCollectionName: events
    snapshotCollectionName: snapshots
  rabbitmq:
    hostname: localhost
  data:
    mongodb:
      uri: mongodb://localhost:27017/users
  profiles:
    active: ${profile:default}

logging:
  level:
    microservices4vaadin: INFO
    com.netflix.discovery: 'OFF'

---
# For deployment in Docker containers
spring:
  profiles: docker
  rabbitmq:
    hostname: rabbitmq
  data:
    mongodb:
      uri: mongodb://mongodb:27017/users
